### ISSUE TITLE
在页面中输入中文添加成功后中文信息显示乱码

### ISSUE THREAD

**Issue by Fangziqiang** [radiateboy/automagic#10]
在页面中输入中文添加成功后中文信息显示乱码，请问这个问题怎么解决

**Comment by radiateboy** [comment]
在创建库的时候，就设置默认字符集为 utf8.
create database test default charset=utf8;

**Comment by Fangziqiang** [comment]
谢谢你    这个问题后来我也发现了是数据的问题   已经解决了    
网站已经搭建起来了   但是还是有点不太会用   这个执行自动化测试的流程是什么，希望您有时间出一个教程，不知道在哪里输入baseurl等信息
