### ISSUE TITLE
希望出一个Python3.0的版本！

### ISSUE THREAD

**Issue by He-haitao** [radiateboy/automagic#16]
Python3.6 不可以用啊，只能是Python2.7了，那个scapy2.3.3的版本不兼容python3，一开始没看清楚，就开始安装了。。。mysql-python也是没有拍一套红的版本都变成了MySQLclient了。

**Comment by radiateboy** [comment]
开发比较久了，好长时间没动了。scapy2.3.3版本升级到2.4.1了。
