### ISSUE TITLE
请问项目在哪里添加呢？

### ISSUE THREAD

**Issue by longweiqiang** [radiateboy/automagic#2]
我需要创建用例，但是前提得有项目；然后我找到系统管理-产品管理中创建了一个产品，再回到创建用例界面，发现下拉框中没有我创建的产品；然后我又到admin后台创建了一个项目，之后在用例界面依然看不到项目，是我的操作方式不对吗？见截图
![1](https://user-images.githubusercontent.com/22344864/38184401-f4f88e44-3679-11e8-8b25-cafb3f650a5b.png)

![2](https://user-images.githubusercontent.com/22344864/38184316-6c239c26-3679-11e8-8562-f61a61f72d3a.png)

![3](https://user-images.githubusercontent.com/22344864/38184317-6c87ecb2-3679-11e8-88c5-b3f015052f8e.png)

**Comment by radiateboy** [comment]
产品管理，点击产品名称进入 可以创建项目, 再点击项目名称，可以创建 模块

**Comment by longweiqiang** [comment]
你好，能出个demo吗？我把automagic\seleniumkeyword\data中的sql导到autoplat_keyword表中了，接下来就不知道怎么做了，测试的url在哪里添加呢？
