### ISSUE TITLE
新增和修改用例后，用例的执行顺序被自动修改

### ISSUE THREAD

**Issue by qinliu1314** [radiateboy/automagic#28]
我在本地部署服务器后，链接本地数据库，使用没有问题，
本地部署服务器，连接线上数据库，就出现新增用例和修改用例后用例执行步骤不对

**Comment by radiateboy** [comment]
@qinliu1314 能详细描述下操作步骤吗？ 我这没能复现。

**Comment by qinliu1314** [comment]
你好，非常感谢！

我是连接的公司服务器数据库和同事机器的数据库，然后本机启动服务后，新增用例并且保存，查看用例的时候，用例的步骤就变了。

比如登录：我是顺序是：1、打开地址；2、输入用户名；3、输入密码；4、提交。但是保存后再次查看，顺序变为：1、输入用户名；2、打开地址；3、输入密码；4、提交，保存后的顺序是随机产生的。没有固定的变化规律。

我连接本机的数据库没有发现该问题。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ray"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 中午11:01
收件人:&nbsp;"radiateboy/automagic"<automagic@noreply.github.com&gt;;
抄送:&nbsp;"柳琴"<1007952767@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [radiateboy/automagic] 新增和修改用例后，用例的执行顺序被自动修改 (#28)





 
@qinliu1314 能详细描述下操作步骤吗？ 我这没能复现。

**Comment by radiateboy** [comment]
@qinliu1314 关闭提交时使用ajax的异步模式，异步模式下可能会导致data数据顺序错乱。

**Comment by qinliu1314** [comment]
非常感谢谢，我明天试一下



---原始邮件---
发件人: "ray"<notifications@github.com&gt;
发送时间: 2020年5月9日(周六) 晚上7:53
收件人: "radiateboy/automagic"<automagic@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"qinliu1314"<1007952767@qq.com&gt;;
主题: Re: [radiateboy/automagic] 新增和修改用例后，用例的执行顺序被自动修改 (#28)




 
关闭提交时使用ajax的异步模式，异步模式下可能会导致data数据顺序错乱。

**Comment by qinliu1314** [comment]
&nbsp;
  你好，我这边还是存在这个问题，配置信息如下：

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"ray"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月9日(星期六) 晚上7:53
 收件人:&nbsp;"radiateboy/automagic"<automagic@noreply.github.com&gt;;
 抄送:&nbsp;"柳琴"<1007952767@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [radiateboy/automagic] 新增和修改用例后，用例的执行顺序被自动修改 (#28)

 

 

 
关闭提交时使用ajax的异步模式，异步模式下可能会导致data数据顺序错乱。

**Comment by qinliu1314** [comment]
&nbsp;
  你好，我这边还是存在这个问题，配置信息如下：
 &nbsp;
 数据库信息：'NAME': 'hd_test',
'USER': 'handi',
'PASSWORD': 'handi123',
'HOST': '106.12.8.159',
'PORT': '3306',

 

 ------------------ 原始邮件 ------------------
  发件人:&nbsp;"ray"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月9日(星期六) 晚上7:53
 收件人:&nbsp;"radiateboy/automagic"<automagic@noreply.github.com&gt;;
 抄送:&nbsp;"柳琴"<1007952767@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [radiateboy/automagic] 新增和修改用例后，用例的执行顺序被自动修改 (#28)

 

 

 
关闭提交时使用ajax的异步模式，异步模式下可能会导致data数据顺序错乱。

**Comment by radiateboy** [comment]
@qinliu1314 ok，我把这个Bug先激活。 
麻烦您试试重新建一个测试用例，然后再试试【复制】一个测试用例、【更新】一个测试用例是不是都会出现这样的问题。
你连接的数据库是外网的吗?

**Comment by qinliu1314** [comment]
&nbsp;
  你好，这些操作我之前都试过，都会出现，我给的数据库是外网的，可以直接连接，你看看是否能重现呢，超管是admin&nbsp;&nbsp; admin123

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"ray"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年5月11日(星期一) 下午3:57
 收件人:&nbsp;"radiateboy/automagic"<automagic@noreply.github.com&gt;;
 抄送:&nbsp;"柳琴"<1007952767@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
 主题:&nbsp;Re: [radiateboy/automagic] 新增和修改用例后，用例的执行顺序被自动修改 (#28)

 

 

 
@qinliu1314 ok，我把这个Bug先激活。
麻烦您试试重新建一个测试用例，然后再试试【复制】一个测试用例、【更新】一个测试用例是不是都会出现这样的问题。
你连接的数据库是外网的吗?

**Comment by radiateboy** [comment]
@qinliu1314 你这个数据库我连不上，显示1045错误，没有访问权限

**Comment by radiateboy** [comment]
已修复 重新对测试步骤在查看、修改、复制页面使用stepid进行排序
