### ISSUE TITLE
期望可以增加使用文档

### ISSUE THREAD

**Issue by lihuacai168** [radiateboy/automagic#30]
已经按照安装文档在本地部署好了，但是不会使用。
- 创建项目，模块是根据issuse中才会新建。可以增加项目和模块关联列表。
- 新增用例，已经导入了所有`insertkeyword.sql`，但找不到打开url，实现登录
- 另外期望可以增加qq交流群或者微信交流群，方便新人入门。

**Comment by radiateboy** [comment]
@lihuacai168  [点击此处查看使用说明](https://github.com/radiateboy/automagic/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)
