### ISSUE TITLE
请问这个系统怎么新建项目啊

### ISSUE THREAD

**Issue by markerpan** [radiateboy/automagic#32]

**Comment by xianminpan** [comment]
![image](https://user-images.githubusercontent.com/29617434/83853204-84c15200-a747-11ea-955a-503a05de2144.png)

**Comment by radiateboy** [comment]
你这个用户没有权限&nbsp;

 &nbsp; シ宥亊蕪亊閙閙`﹎〆&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;シ訫煩也偠笑笑`﹎〆
 ================================================
Ray
 mail：tsbc@vip.qq.com
 QQ:88255791
 空间：http://tsbc520.qzone.qq.com
Blog：http://www.cnblogs.com/tsbc
Coding：https://coding.net/u/tsbc


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xianminpan"<notifications@github.com&gt;; 
发送时间: 2020年6月5日(星期五) 下午4:14
收件人: "radiateboy/automagic"<automagic@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [radiateboy/automagic] 请问这个系统怎么新建项目啊 (#32)





 

 
&mdash;

**Comment by radiateboy** [comment]
@xianminpan 使用createsuperuser 创建 帐号登录后，在 系统管理-用户管理中 启用用户的 管理权限

**Comment by markerpan** [comment]
嗯，可以了，谢谢！
