### ISSUE TITLE
设置了case依赖不起效

### ISSUE THREAD

**Issue by metoto** [radiateboy/automagic#34]
我创建了2个用例，第一个是登录，第二个是登录后操作菜单，但是在创建任务去运行第2个用例时，不会自动先跑第一个登录用例。

![image](https://user-images.githubusercontent.com/5674572/84460265-170fab80-ac9c-11ea-9723-62207dd700bd.png)

![image](https://user-images.githubusercontent.com/5674572/84460299-28f14e80-ac9c-11ea-8bda-a3cc14685055.png)

**Comment by radiateboy** [comment]
@metoo 感谢您的反馈。因为考虑到依赖用例填写过于开放，可能会导致闭环，所以该功能在task中不能使用。只在用例列表页面点击单个用例执行的时候有效

**Comment by metoto** [comment]
请问可以加你QQ么？我有一些使用方面的问题想请教~~

**Comment by radiateboy** [comment]
我笔记本系统上不了QQ，你可以直接发邮件我方便回复你&nbsp;

 &nbsp; シ宥亊蕪亊閙閙`﹎〆&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;シ訫煩也偠笑笑`﹎〆
 ==========================================
Ray
 mail：tsbc@vip.qq.com
 QQ:88255791
Blog：http://www.cnblogs.com/tsbc
Coding：https://github.com/radiateboy/automagic


&nbsp;




------------------&nbsp;Original&nbsp;------------------
