### ISSUE TITLE
无法选择项目

### ISSUE THREAD

**Issue by yeducom** [radiateboy/automagic#6]
![121](https://user-images.githubusercontent.com/18734187/38231030-55fc91bc-3743-11e8-8a06-b03bca33d4f9.png)

**Comment by zerolugithub** [comment]
![tt](https://user-images.githubusercontent.com/10940721/38243470-323637e8-376a-11e8-86b8-96673480866f.jpg)
你的创建关联，就是说创建产品后，点击产品创建项目，然后在创建模块才能使用
