### ISSUE TITLE
autoplat_userandproduct这张表在创建产品的时候没有写入关联信息

### ISSUE THREAD

**Issue by EdelweissCjw** [radiateboy/automagic#7]
创建产品之后autoplat_userandproduct这张表没有创建关联信息，导致页面上项目以及产品出不来，检查代码之后发现：
![image](https://user-images.githubusercontent.com/38028363/38231667-31a954f0-3746-11e8-90e3-5a448bf5dd74.png)
上图中的添加产品方法没有关于autoplat_userandproduct表的修改，不太明白是什么原因，手动往表里面添加关联信息之后，页面的显示就正常了，尝试增加方法之后可以解决这个问题，请作者解惑

**Comment by radiateboy** [comment]
用户管理 界面 右上角有个 产品关联 按钮，可以进行用户和产品的关联
